### ISSUE TITLE
Setup Cloud Anchors so that Any Device Can Use

### ISSUE THREAD

**Issue by Angelica-P** [SEG491X-Team16/uOttawa-Live-Tour#23]
Right now only registered devices can use Cloud Anchors but we aren't going to able to register every device that downloads our app.

**Comment by loicdrbx** [comment]
To be more precise, only APK files signed with a registered keystore are authorized to make calls to the cloud anchors API.

In order to make calls to the API during development, we must all:
  1. Share the same debug.keystore among ourselves, or
  2. Add each of our individual keystores to the list of authorized clients

The release versions of the app will all be signed with the same keystore and will not be subject to this issue. For now we have gone with option 1.
